name: Build Latest

on:
  workflow_dispatch:
    inputs:
      doRelease:
        description: 'Publish new release'
        type: boolean
        default: false
        required: false
      tag:
        type: string
        description: 'Release version tag (e.g. v0.2.1-beta)'
        required: true
      ref:
        type: string
        description: 'Git ref from which to release'
        required: true
        default: 'main'

env:
  DOTNET_SDK_VERSION: "9.0.101"
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  set-date:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.get_date.outputs.date }}
      tag: ${{ steps.format_tag.outputs.tag }}
    steps:
      - name: Get Date in UTC+8
        id: get_date
        run: |
          DATE=$(date -u -d '8 hours' +'%Y%m%d')
          echo "date=${DATE}" >> "$GITHUB_OUTPUT"

      - name: Determine Tag
        id: format_tag
        run: |
          if [ "${{ github.event.inputs.doRelease }}" == "true" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="actions-$GITHUB_RUN_ID"
          fi
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

  build-win-nt6_0-x86:
    runs-on: windows-latest
    needs: set-date

    steps:
      - uses: actions/checkout@v1

      - name: Install zip
        run: choco install zip --no-progress --yes

      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - run: powershell -Command "(Get-Content src/N_m3u8DL-RE/N_m3u8DL-RE.csproj) -replace '<TargetFramework>.*</TargetFramework>', '<TargetFramework>net9.0-windows</TargetFramework>' | Set-Content src/N_m3u8DL-RE/N_m3u8DL-RE.csproj"
      - run: dotnet add src/N_m3u8DL-RE/N_m3u8DL-RE.csproj package YY-Thunks --version 1.1.4
      - run: dotnet add src/N_m3u8DL-RE/N_m3u8DL-RE.csproj package VC-LTL --version 5.1.1
      - run: dotnet publish src/N_m3u8DL-RE -p:TargetPlatformMinVersion=6.0 -r win-x86 -c Release -o artifact-x86

      - name: Package [win-x86]
        run: |
          cd artifact-x86
          zip ../N_m3u8DL-RE_${{ needs.set-date.outputs.tag }}_win-NT6.0-x86_${{ needs.set-date.outputs.date }}.zip N_m3u8DL-RE.exe

      - name: Upload Artifact[win-x86]
        uses: actions/upload-artifact@v4
        with:
          name: win-NT6.0-x86
          path: N_m3u8DL-RE_${{ needs.set-date.outputs.tag }}_win-NT6.0-x86_${{ needs.set-date.outputs.date }}.zip

  build-linux-musl-x64:
    runs-on: ubuntu-latest
    needs: set-date
    container: mcr.microsoft.com/dotnet/sdk:9.0-alpine-amd64

    steps:
      - uses: actions/checkout@v1

      - run: apk add clang build-base zlib-dev
      - run: dotnet publish src/N_m3u8DL-RE -r linux-musl-x64 -c Release -o artifact -p:InvariantGlobalization=true

      - name: Package [linux-musl-x64]
        run: |
          cd artifact
          tar -czvf ../N_m3u8DL-RE_${{ needs.set-date.outputs.tag }}_linux-musl-x64_${{ needs.set-date.outputs.date }}.tar.gz N_m3u8DL-RE

      - name: Upload Artifact [linux-musl-x64]
        uses: actions/upload-artifact@v4
        with:
          name: linux-musl-x64
          path: N_m3u8DL-RE_${{ needs.set-date.outputs.tag }}_linux-musl-x64_${{ needs.set-date.outputs.date }}.tar.gz

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.inputs.doRelease == 'true' }}
    needs: [set-date,build-win-nt6_0-x86,build-linux-musl-x64]
    
    steps:
      - name: Fetch artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: N_m3u8DL-RE_${{ github.event.inputs.tag }}
          artifacts: "android-bionic-x64/*,android-bionic-arm64/*,linux-x64/*,linux-arm64/*,linux-musl-x64/*,linux-musl-arm64/*,osx-x64/*,osx-arm64/*,win-x64/*,win-arm64/*,win-NT6.0-x86/*"
          draft: false
          allowUpdates: true
          generateReleaseNotes: true
          discussionCategory: 'Announcements'
